param(
    [string]$ScriptsPath = "C:\Run_in_Sandbox\startup-scripts",
    # Can include this switch when running from the .wsb file to indicate it's the first launch of the sandbox
    # Useful if re-running this script within the sandbox as a test, but don't want certain parts to run again
    [switch]$launchingSandbox
)

# IMPORTANT!!!
# Do not edit this file; its replaced on EVERY start of the sandbox
# Code is generated by Modules/Runtime/StartupScripts.psm1

# Read Hide_Powershell configuration from Sandbox_Config.xml
# This allows standalone execution to respect the user's preference
$Sandbox_Root_Path = "C:\Run_in_Sandbox"
$ConfigPath = Join-Path $Sandbox_Root_Path "Sandbox_Config.xml"
$Hide_Powershell = "True"  # Default to hidden

if (Test-Path -LiteralPath $ConfigPath) {
    try {
        $config = [xml](Get-Content -LiteralPath $ConfigPath -Raw)
        $configValue = $config.Configuration.Hide_Powershell
        if (-not [string]::IsNullOrEmpty($configValue)) {
            $Hide_Powershell = $configValue
        }
    } catch {
        Write-Warning "[Orchestrator] Failed to read config file: $($_.Exception.Message). Using default (Hidden)."
    }
}

# Always use /c for non-blocking execution - errors are shown via message box
# The CMD wrapper is always hidden - only actual installers should be visible
$CmdSwitch = "/c"
$ShowErrors = ($Hide_Powershell -eq "False")

# ------ Check that we're running in the Windows Sandbox ------
# This script is intended to be run from within the Windows Sandbox. We'll do a rudamentary check for if the current user is named "WDAGUtilityAccount"
if ($env:USERNAME -ne "WDAGUtilityAccount") {
    Write-host "`n`nERROR: This script is intended to be run from WITHIN the Windows Sandbox.`nIt appears you are running this from outside the sandbox.`n" -ForegroundColor Red
    Write-host "`nPress Enter to exit." -ForegroundColor Yellow
    Read-Host
    exit
}

Write-Host "[Orchestrator] Scripts path: $ScriptsPath"
Write-Host "[Orchestrator] Hide_Powershell: $Hide_Powershell (ShowErrors: $ShowErrors)"

# Load Windows Forms for error dialogs
[System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms") | Out-Null

# Create a hidden topmost form to use as MessageBox owner (ensures dialogs appear on top)
$topmostForm = New-Object System.Windows.Forms.Form
$topmostForm.TopMost = $true
$topmostForm.ShowInTaskbar = $false
$topmostForm.WindowState = [System.Windows.Forms.FormWindowState]::Minimized

# 1) Run ordered startup scripts: 00-*, 01-* ... 99-*
$pattern = '^\d{2}-.+\.ps1$'
$items = Get-ChildItem -LiteralPath $ScriptsPath -Filter *.ps1 -File -ErrorAction SilentlyContinue |
         Where-Object { $_.Name -match $pattern } |
         Sort-Object Name

foreach ($i in $items) {
    Write-Host "[Orchestrator] Running: $($i.Name)"
    try {
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $i.FullName
        $rc = $LASTEXITCODE
        if ($rc -ne $null -and $rc -ne 0) {
            Write-Warning "[Orchestrator] Script $($i.Name) returned exit code $rc"
        }
    } catch {
        Write-Warning "[Orchestrator] Script $($i.Name) threw: $($_.Exception.Message)"
    }
}

# Restart Explorer so changes take effect
Write-Host "[Orchestrator] Restarting Explorer so changes take effect"
Get-Process explorer | Stop-Process -Force

# 2) Read and run the original command last
$origFile = Join-Path $ScriptsPath "OriginalCommand.txt"
if (Test-Path -LiteralPath $origFile) {
    $orig = (Get-Content -LiteralPath $origFile -Raw).Trim()
    Write-Host "[Orchestrator] Running original command..."
    Write-Host "[Orchestrator] Command: $orig"
    
    # Check if the command is a PowerShell command - run it directly without CMD wrapper
    if ($orig -match '^C:\\Windows\\.*\\powershell\.exe') {
        # Extract the PowerShell executable and arguments
        # The command format is: C:\Windows\...\powershell.exe <args>
        $parts = $orig -split ' ', 2
        $psExe = $parts[0]
        $psArgs = if ($parts.Length -gt 1) { $parts[1] } else { "" }
        
        Write-Host "[Orchestrator] Detected PowerShell command, running directly..."
        $process = Start-Process -FilePath $psExe -ArgumentList $psArgs -Wait -PassThru
    } else {
        # Run through cmd to support cmd-style commands
        # Always use /c and Hidden for the CMD wrapper - only the actual command output matters
        $process = Start-Process -FilePath "C:\Windows\SysWOW64\cmd.exe" -ArgumentList "$CmdSwitch $orig" -WindowStyle Hidden -Wait -PassThru
    }
    
    # Show error dialog if execution failed and Hide_Powershell is False
    if ($process.ExitCode -ne 0 -and $ShowErrors) {
        $topmostForm.Show()
        $topmostForm.Activate()
        [System.Windows.Forms.MessageBox]::Show(
            $topmostForm,
            "Command execution failed`nExit code: $($process.ExitCode)`nCommand: $orig",
            "Execution Error",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        ) | Out-Null
        $topmostForm.Hide()
    }
} else {
    Write-Warning "[Orchestrator] OriginalCommand.txt not found; nothing to run."
}
